github.com:
    users:
        quanghai2k4:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: quanghai2k4
